### ISSUE TITLE
LAN IP not found

### ISSUE THREAD

**Issue by cauwelsdev** [lordkator/ZonamaDev#111]
Can't find LAN IP in VM. From IRC we tried:
sudo traceroute -I www.cisco.com
&
sudo traceroute -nI www.cisco.com
both worked for the IP's.

**Comment by karlbunch** [comment]
Should work now, to test try:

zdcfg clear iplist;zdcfg clear server_ip;swgemu stop;sudo init 6

When you boot again the LAN IP should show in the list of options.

**Comment by cauwelsdev** [comment]
No, didn't fix it still getting only Default, Public Internet IP, and Manual for options.
Did a vm shutdown, then vagrant destroy to start with a clean slate. Then did a git fetch, git status (was 27 rev. behind), git pull to get updated.
Ran ./setup.sh and got the above once on IP selection.

**Comment by karlbunch** [comment]
He @cauwelsdev can you do this for me, on the guest:

zdcfg clear iplist;zdcfg clear server_ip;swgemu stop;sudo init 6

AFTER it shows the prompt with the IP's in a terminal:

```
sudo gem install gist
gist /tmp/iplist.out
```

And share the URL of the gist.

**Comment by cauwelsdev** [comment]
iplist.out: https://gist.github.com/359c7cae0ba6f755d9d5

local guess_lan_router=$(sudo traceroute -I -nw 2 -q 2 -m 10 www.cisco.com | perl -ne '@a = split; if($a[1] =~ /'${regex}'/) {  print $p; exit(0) }; $p = $a[1];')

**Comment by karlbunch** [comment]
What does this return:

```
sudo traceroute -I -nw 2 -q 2 -m 10 www.cisco.com
````

**Comment by cauwelsdev** [comment]
https://gist.github.com/cauwelsdev/24f5d551ecb0317a1afe

**Comment by karlbunch** [comment]
Output of:

```
sudo traceroute -I -nw 2 -q 2 -m 10 www.cisco.com | perl -ne 'push(@a,(split)[1]); END { while(@a) { shift(@a); if($a[0] =~ /^10\.0\.2\./) { print($a[1] . "\n"); exit(0); } } }'
```

**Comment by cauwelsdev** [comment]
192.168.1.1

**Comment by karlbunch** [comment]
Hey @cauwelsdev I think 8f0d02a37952010c1d1ccc7b4e66f20cb3f6381c will fix this.

I tested several different configurations including adding a bridged interface etc.

I'm closing for now, please comment once you've had a chance to test and let me know if this fixes your issue with Charter's strange network topology.

**Comment by cauwelsdev** [comment]
left a message in IRC for you @karlbunch
